version: '3.8'

services:
  server:
    image: myimage/tests:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend_network

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - weather_server
      - reserve_weather_server
    networks:
      - backend_network

  weather_server:
    build:
      context: .
      dockerfile: docker/weather_server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend_network

  reserve_weather_server:
    build:
      context: .
      dockerfile: docker/reserve_weather_server/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
